config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :polygons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/Address.rb
class Address
  include ::ActiveJsonModel::Model

  json_attribute :street, String
  json_attribute :city, String
  json_attribute :zipcode, String
  json_attribute :state, String, validation: {inclusion: {in: %w[AK AL AR AS AZ CA CO CT DC DE FL GA GU HI IA ID IL IN KS KY LA MA MD ME MI MN MO MP MS MT NC ND NE NH NJ NM NV NY OH OK OR PA PR RI SC SD TN TX UM UT VA VI VT WA WI WV WY] }}
end

app/models/BaseCredential.rb
class BaseCredential
  include ::ActiveJsonModel::Model

  json_attribute :type
  json_polymorphic_via do |data|
    if data[:type] == 'username_password'
      UsernamePasswordCredential
    else
      OauthTokenCredential
    end
  end
end

app/models/ContactMethod.rb
class ContactMethod
  include ::ActiveJsonModel::Model

  # This is designed to test a case where there isn't a parent/child
  # relationship between this class and the concrete ones
  json_polymorphic_via do |data|
    if data[:street]
      Address
    else
      Email
    end
  end
end

app/models/Credentials.rb
class Credentials
  include ::ActiveJsonModel::Array

  json_array_of BaseCredential
end

app/models/Email.rb
class Email
  include ::ActiveJsonModel::Model

  json_attribute :email, String
  json_attribute :label, String
end

app/models/OauthTokenCredential.rb
class OauthTokenCredential < BaseCredential
  json_fixed_attribute :type, value: 'oauth_token'
  json_attribute :access_token, String
  json_attribute :refresh_token, String
end

app/models/Point.rb
class Point
  include ::ActiveJsonModel::Model

  json_attribute :x, Integer
  json_attribute :y, Integer
end

app/models/Points.rb
class Points
  include ::ActiveJsonModel::Array

  json_array_of Point
end

app/models/UsernamePasswordCredential.rb
class UsernamePasswordCredential < BaseCredential
  json_fixed_attribute :type, value: 'username_password'
  json_attribute :username, String
  json_attribute :password, String
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/polygon.rb
class Polygon < ApplicationRecord
  attribute :points, Points.attribute_type
end

app/models/user.rb
class User < ApplicationRecord
  attribute :credentials, BaseCredential.encrypted_attribute_type
  attribute :previous_credentials, Credentials.encrypted_attribute_type
  attribute :address, Address.attribute_type
  attribute :contact_method, ContactMethod.attribute_type
  attribute :secret_contact_method, ContactMethod.attribute_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/polygons_controller.rb
class PolygonsController < ApplicationController
  before_action :set_polygon, only: %i[ show edit update destroy ]

  # GET /polygons or /polygons.json
  def index
    @polygons = Polygon.all
  end

  # GET /polygons/1 or /polygons/1.json
  def show
  end

  # GET /polygons/new
  def new
    @polygon = Polygon.new
  end

  # GET /polygons/1/edit
  def edit
  end

  # POST /polygons or /polygons.json
  def create
    @polygon = Polygon.new(polygon_params)

    respond_to do |format|
      if @polygon.save
        format.html { redirect_to polygon_url(@polygon), notice: "Polygon was successfully created." }
        format.json { render :show, status: :created, location: @polygon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @polygon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polygons/1 or /polygons/1.json
  def update
    respond_to do |format|
      if @polygon.update(polygon_params)
        format.html { redirect_to polygon_url(@polygon), notice: "Polygon was successfully updated." }
        format.json { render :show, status: :ok, location: @polygon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @polygon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polygons/1 or /polygons/1.json
  def destroy
    @polygon.destroy

    respond_to do |format|
      format.html { redirect_to polygons_url, notice: "Polygon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_polygon
      @polygon = Polygon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def polygon_params
      params.require(:polygon).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polygons_helper.rb
module PolygonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActivejsonmodelRailsTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/polygons/_form.html.erb
<%= form_with(model: polygon) do |form| %>
  <% if polygon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(polygon.errors.count, "error") %> prohibited this polygon from being saved:</h2>

      <ul>
        <% polygon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/polygons/_polygon.html.erb
<div id="<%= dom_id polygon %>">
  <p>
    <strong>Name:</strong>
    <%= polygon.name %>
  </p>

</div>

app/views/polygons/edit.html.erb
<h1>Editing polygon</h1>

<%= render "form", polygon: @polygon %>

<br>

<div>
  <%= link_to "Show this polygon", @polygon %> |
  <%= link_to "Back to polygons", polygons_path %>
</div>

app/views/polygons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Polygons</h1>

<div id="polygons">
  <% @polygons.each do |polygon| %>
    <%= render polygon %>
    <p>
      <%= link_to "Show this polygon", polygon %>
    </p>
  <% end %>
</div>

<%= link_to "New polygon", new_polygon_path %>

app/views/polygons/new.html.erb
<h1>New polygon</h1>

<%= render "form", polygon: @polygon %>

<br>

<div>
  <%= link_to "Back to polygons", polygons_path %>
</div>

app/views/polygons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @polygon %>

<div>
  <%= link_to "Edit this polygon", edit_polygon_path(@polygon) %> |
  <%= link_to "Back to polygons", polygons_path %>

  <%= button_to "Destroy this polygon", @polygon, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>